version: 0.0
os: linux
files:
  - source: ./contents
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/uninstall.sh
      timeout: 3000
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 3000
      runas: root
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 300
      runas: root
